services:
  frontend:
    image: kinsey05/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8083:8080"  # 这里改成 8083，这样你浏览器访问 8083 才是对的
    environment:
      # 注意：后面这里要指向后端的端口，通常是 8082
      - VITE_GRAPHQL_URI=http://52.71.22.95:8082/graphql
      - VITE_SERVER_URI=http://52.71.22.95:8082
    restart: unless-stopped